<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WMS_RadiadoresLemos_WPF</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Wallet\**" />
    <EmbeddedResource Remove="Wallet\**" />
    <None Remove="Wallet\**" />
    <Page Remove="Wallet\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.50" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="23.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Oracle\network\admin\" />
  </ItemGroup>

</Project>
